name: danger

on:
  pull_request

jobs:
  danger:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Danger Swift
      uses: danger/swift@2.0.1
      env:
        GITHUB_TOKEN: ${{ secrets.DangerGitHubAPIToken }}
